name: Deploy to Locaweb

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install FTP deployer
      run: sudo apt-get install lftp

    - name: Deploy to Locaweb
      env:
        FTP_HOST: ${{ secrets.HOST }}
        FTP_USERNAME: ${{ secrets.USER }}
        FTP_PASSWORD: ${{ secrets.PASS }}
      run: |
        lftp -c "open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST; mirror -R ./ /home/frostboss1/"
