name: Deploy to Locaweb

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install FTP deployer
      run: sudo apt-get install lftp

    - name: FTP Deploy Locaweb
      uses: locaweb/ftp-deploy@1.0.0
      with:
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USER }}
        password: ${{ secrets.PASS }}
        localDir: "home"
